import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import styles from "@/styles/Home.module.css";

const Layout = ({children}: any) => {
    return (
      <>
        <Head>
          <title>WalletConnect | Next Starter Template</title>
          <meta name="description" content="Generated by create-wc-dapp" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className={styles.main}>
          <div className={styles.wrapper}>{children}</div>
        </main>
        <Footer/>
      </>
    );
};

export default Layout;
